apiVersion: v1
kind: Secret
metadata:
  name: grackle-twitter-credentials
  labels:
    app: grackle
    environment: demo
type: Opaque
data:
  twitter-access-token: bXktdHdpdHRlci1hY2Nlc3MtdG9rZW4K
  twitter-access-secret: bXktdHdpdHRlci1hY2Nlc3Mtc2VjcmV0Cg==
  twitter-consumer-key: bXktdHdpdHRlci1jb25zdW1lci1rZXkK
  twitter-consumer-secret: bXktdHdpdHRlci1jb25zdW1lci1zZWNyZXQK
