apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grackle-web
  labels:
    app: grackle
    component: web
    environment: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grackle
      component: web
      environment: demo
  template:
    metadata:
      labels:
        app: grackle
        component: web
        environment: demo
    spec:
      containers:
      - name: grackle
        image: quay.io/jmckind/grackle:latest
        command:
          - /grackle-web
        env:
          - name: GRK_LOG_LEVEL
            value: "debug"
          - name: GRK_RETHINKDB_HOST
            value: "grackle-rethinkdb"
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grackle
  namespace: grackle
  labels:
    app: grackle
    environment: demo
spec:
  type: NodePort
  selector:
    app: grackle
    component: web
    environment: demo
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8000
